name: "Update Version v0.9"

on:
  schedule:
    # Runs every 15 minutes
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: versionupdater

      - name: Download JSON and extract version
        run: |
          curl https://itunes.apple.com/lookup?id=1348640525 -o app_info.json
          VERSION=$(jq -r '.results[0].version' app_info.json)
          echo "$VERSION" > currentVersion.txt

      - name: Commit and push new version
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add currentVersion.txt
          git commit -m "Update app version to $VERSION" -a || echo "No changes to commit."
          git push
